### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by kravietz** [agl/extract-nss-root-certs#1]
$ 8g convert_mozilla_certdata.go
convert_mozilla_certdata.go:172: too many arguments in call to hash.Sum
convert_mozilla_certdata.go:278: undefined: strconv.ParseUint
convert_mozilla_certdata.go:295: undefined: io.EOF

**Comment by agl** [comment]
These result from using r60 (the release branch) rather than Go 1 (which is very nearly the new release branch).

Cloning the Go repo without "-u release" and rebuilding will fix it.
