### ISSUE TITLE
Read whole input and failed to find beginning of license

### ISSUE THREAD

**Issue by sphr2k** [agl/extract-nss-root-certs#2]
Finally got my Go installation working (mingw64) but only get the following error when trying to run extract-nss-root-certs:

Read whole input and failed to find beginning of license
exit status 1

Am I doing something wrong?

**Comment by agl** [comment]
You're not doing anything wrong. It looks like Mozilla updated the license and removed the markers in the file:

http://bonsai.mozilla.org/cvsview2.cgi?diff_mode=context&whitespace_mode=show&file=certdata.txt&branch=&root=/cvsroot&subdir=mozilla/security/nss/lib/ckfw/builtins&command=DIFF_FRAMESET&rev1=1.82&rev2=1.83

I've pushed an update to address this. If you pull and run it again, it should work.
