### ISSUE TITLE
2012/04/30 18:21:27 Failed to parse certificate ... negative serial number

### ISSUE THREAD

**Issue by sphr2k** [agl/extract-nss-root-certs#3]
Using the current certdata.txt

```
CVS_ID "@(#) $RCSfile: certdata.txt,v $ $Revision: 1.83 $ $Date: 2012/04/25 14:49:29 $"
```

everything works well except for one certificate not being converted:

```
2012/04/30 18:21:27 Failed to parse certificate starting on line 23068: negative serial number
```

This is a certificate named "EC-ACC", its serial number is "EE:2B:3D:EB:D4:21:DE:14:A8:62:AC:04:F3:DD:C4:01"

**Comment by agl** [comment]
Yes, that certificate is invalid and isn't expected to be converted. Last I heard, Kathleen said that the CA was going to refresh it in the coming months.

**Comment by sphr2k** [comment]
Ok, thanks for clarifying and thanks for fixing issue #2 so quickly.
